name: Hourly sync of NuGet catalog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'

      - name: Install required packages
        run: pip install requests==2.32.5 aboutcode.pipeline==0.2.1

      - name: Run sync
        run: python sync_catalog.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "AboutCode Automation"
          git config user.email "automation@aboutcode.org"
          git add -A
          timestamp=$(date -u)
          git commit -m "$(echo -e "Sync NuGet catalog: $timestamp\n\nSigned-off-by: AboutCode Automation <automation@aboutcode.org>")" || exit 0
          git push
